
version: '3.8'

services:

  postgres:
    image: ankane/pgvector
    container_name: rag-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ragdb

    ports:
      - "5432:5432"
